version: '3.7'
services:
  es:
    build:
      context: .
      args:
        ELK_VERSION: 8.11.1
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200 #https (client-node)
      - 9300:9300 #tcp (node-node)
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.10.4
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - es-bridge
    depends_on:
      - es


networks:
  es-bridge:
    driver: bridge
